services:
  huguette:
    image: ghcr.io/hug-efrei/huguette:latest
    build: .
    container_name: huguette
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
